### ISSUE TITLE
implementation of setsatatus

### ISSUE THREAD

**Issue by abhishek45654** [abhishek45654/dummyapis#1]
build an api to set the status of payment

**Comment by navneet35** [comment]
hi,
can you please explain the issue and assign it to me.

**Comment by abhishek45654** [comment]
> hi, can you please explain the issue and assign it to me.

hey Navneet35,
This is assignment project which is for practice of java spring boot. This will not be continued furthur due to some internal reasons. Bye the way thanks for your interest.
